sudo: required
dist: trusty
language: node_js
env:
  global:
    - CI_DIR=.ci_config
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
    - ROS_DISTRO=kinetic
node_js:
  - "0.10"   # ubuntu 14.04
  - "4"      # ubuntu 16.04
  - 'stable'
  - 'lts/*'
matrix:
  fast_finish: true
  allow_failures:
    - env: ROS_DISTRO=kinetic
    - node_js: "0.10"  # builtin nodejs on ubuntu 14.04 is too old
install:
  # Force travis to use its minimal image with default Python settings
  - sudo rm -fr /opt/python/
  - export DEBIAN_FRONTEND=noninteractive
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
before_script:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq || echo Ignore error on apt-get update
  - sudo apt-get install -qq -y firefox xvfb
  - sudo apt-get install -qq -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool 
  - sudo apt-get install -qq -y ros-$ROS_DISTRO-ros ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-common-tutorials ros-$ROS_DISTRO-rospy-tutorials ros-$ROS_DISTRO-actionlib-tutorials
  - sudo apt-get install -qq -y ros-$ROS_DISTRO-rosbridge-server ros-$ROS_DISTRO-tf2-web-republisher 
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Only update npm in the 0.8 and 0.10 versions to not run into this issue:
  #   https://github.com/nodejs/node/issues/433
  - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm update -g npm ;; esac
  # Set up Xfvb for Firefox headless testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Setup Catkin workspace
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws && catkin init
  - wstool init src
  - wstool merge -t src ${CI_SOURCE_PATH}/.rosinstall
  - wstool update -t src
  - ln -s $CI_SOURCE_PATH src/${REPOSITORY_NAME}
  - ls -al src/
  - wstool info -t src
  - sudo rosdep init || (sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list && sudo rosdep init)
  - rosdep update
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -r -n -y
script:
  - catkin build
  - source devel/setup.bash
  - npm install -g grunt-cli
  - cd src/visualization_rwt/rwt_plot/utils
  - npm install .
  - grunt build
  - chmod +x $CI_SOURCE_PATH/.deploy.sh
jobs:
  include:
    stage: deploy
    provider: script
    script: $CI_SOURCE_PATH/.deploy.sh
    skip_cleanup: true
    on:
      branch: deploy
    env: ROS_DISTRO=kinetic
    node_js: '4'
